-- load files
require("options")
require("plugins")
require("theme")
require("center")
require("lsp")
require("treesitter")
require("cmp")
require("git")
require("navigation")
require("ai")
require("diagnostics")
require("linting")
require("formatting")
require("autocmds")
require("keymaps")
