require("tree-sitter-manager").setup({
	auto_install = true,
	noauto_install = { "c", "lua", "markdown", "markdown_inline", "query", "vim", "vimdoc" },
	ensure_installed = {
		"html",
		"css",
		"scss",
		"javascript",
		"typescript",
		"tsx",
		"cpp",
		"c_sharp",
		"java",
		"python",
		"rust",
		"bash",
		"go",
		"json",
		"toml",
		"make",
		"regex",
		"yaml",
		"nix",
		"gitignore",
		"ini",
		"terraform",
		"jinja",
	},
})
